# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-ORM-Declarative
version:      0.10
version_from: lib/DBIx/ORM/Declarative.pm
installdirs:  site
requires:
    DBI:                           1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
