---
name: DBIx-ORM-Declarative
version: 0.20
author:
  - 'Jim Schneider <perl@jrcsdevelopment.com>'
abstract: Perl extension for object-oriented database access
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1.3
  Scalar::Util: 1
provides:
  DBIx::ORM::Declarative:
    file: lib/DBIx/ORM/Declarative.pm
    version: 0.20
  DBIx::ORM::Declarative::JRow:
    file: lib/DBIx/ORM/Declarative/JRow.pm
  DBIx::ORM::Declarative::Join:
    file: lib/DBIx/ORM/Declarative/Join.pm
  DBIx::ORM::Declarative::Row:
    file: lib/DBIx/ORM/Declarative/Row.pm
  DBIx::ORM::Declarative::Schema:
    file: lib/DBIx/ORM/Declarative/Schema.pm
  DBIx::ORM::Declarative::Table:
    file: lib/DBIx/ORM/Declarative/Table.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
